accounts/urls.py
from django.urls import path
from .views import *
from . import views
app_name = 'accounts'
urlpatterns = [
    path('doctor/',views.doctor_list,name='doctor_list'),
    path('login',views.user_login,name='user_login'),
    path('signup',views.signUp,name='signUp'),
    path('doctor/myprofile',views.myProfile,name='myProfile'),
    path('doctor/updateProfile',views.updateProfile,name='updateProfile'),
    path('doctor/<slug:slug>/',views.doctor_details,name='doctor_details'),
]

vezetaproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls'), name='accounts'),
] 
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.utils.translation import gettext as _


TYPE_OF_PERSON =(
    ( 'M' , "Male"),
    ( 'F' , "Female"),
    )

class Profile(models.Model):

    DOCTOR_IN={
        ( "جلدية" , "جلدية"),
        ( "أسنان" , "أسنان"),
        ( "نفسي" , "نفسي"),
        ( "أطفال حديثي الولادة"  , "أطفال حديثي الولادة"),
        ( "مخ وأعصاب"  , "مخ وأعصاب"),
        (  "عظام" , "عظام"),
        ( "نساء وتوليد"  , "نساء وتوليد"),
        ( "أنف وأذن وحنجرة"   , "أنف وأذن وحنجرة"),
        ( "قلب وأوعيه دموية"   , "قلب وأوعيه دموية"),
        ( "أمراض دم" , "أمراض دم"),
        ( "أورام" , "أورام"),
        ( "باطنة" , "باطنة"),
        ( "تخسيس وتغذية"  , "تخسيس وتغذية"),
        ( "جراحة أطفال"  , "جراحة أطفال"),
        ( "جراحة أورام"  , "جراحة أورام"),
        ( "جراحة أوعيه دموية"   , "جراحة أوعيه دموية"),
        ( "جراحة تجميل"  , "جراحة تجميل"),
        ( "جراحة سمنة ومناظير "   , "جراحة سمنة ومناظير "),
    }
    user            = models.OneToOneField(User,  on_delete=models.CASCADE)
    who_i           = models.TextField(_("من انا"), max_length=250)
    name            = models.CharField(_("الإسم رابعى"), max_length=50)
    surname         = models.CharField(_("اللقب"), max_length=20, blank=True, null=True) 
    subtitle        = models.TextField(_("نبذه عنك"), max_length=70, blank=True, null=True)
    address         = models.CharField(_("المحافظه"), max_length=30, blank=True, null=True)
    address_detail  = models.CharField(_("العنوان بالتفصيل"), max_length=25, blank=True, null=True)
    price           = models.IntegerField(_("سعر الكشف"), blank=True, null=True)
    number_phone    = models.CharField(_("رقم الهاتف"), max_length=50, blank=True, null=True)
    working_hours   = models.CharField(_("عدد ساعات العمل"), max_length=50, blank=True, null=True)
    img           = models.ImageField(_("profile_image"), blank=True, null=True)
    Waiting_time    = models.IntegerField(_("مده الانتظار"), blank=True, null=True)
    facebook        = models.CharField(max_length=100 , blank=True, null=True)
    twitter         = models.CharField(max_length=100 , blank=True, null=True)
    google          = models.CharField(max_length=100 , blank=True, null=True)
    join_us         = models.DateTimeField(_("وقت الانضمام") ,auto_now_add=True ,blank=True, null=True)
    type_doctors    = models.CharField(_("النوع"), choices=TYPE_OF_PERSON, default='M' ,max_length=20, blank=True, null=True)
    doctor          = models.CharField(_("دكتور ؟"),choices=DOCTOR_IN , max_length=50, blank=True, null=True)
    Specialist_doctor = models.CharField(_("متخصص فى ؟"), max_length=50, blank=True, null=True)
    rating          = models.PositiveIntegerField(_("التقييم"),default=0, blank=True, null=True)
    slug            = models.SlugField(_("slug") , blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)


    def __str__(self):
        return '%s' %(self.user.username)

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'
    
def create_profile(sender , **kwargs):
    if kwargs['created']:
        Profile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile, sender=User)





class Comment(models.Model):
    comment     = models.ForeignKey('Profile' , related_name="author", on_delete=models.CASCADE, null=True, blank=True)
    create_at   = models.DateTimeField(auto_now_add=True , blank=True, null=True)
    name        = models.CharField(_("الإسم"), max_length=50)
    email       = models.EmailField(_("الإيميل"), max_length=50)
    comments    = models.TextField(_("التعليق") , max_length=250)

    def __str__(self):
        return '%s' %(self.name)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        ordering = ('-create_at',)

class Appointment(models.Model):
    doctor      = models.ForeignKey('Profile',related_name="doc" , verbose_name=_("doctor"), on_delete=models.CASCADE  , blank=True, null=True)
    name        = models.CharField(_("الإسم") , max_length=100)
    number      = models.CharField(_("رقم الهاتف") , max_length=20)
    email       = models.EmailField(_("الإيميل"), max_length=50)
    read        = models.BooleanField(_("تمت القراءة"), blank=True, null=True)

    def __str__(self):
        return self.name



class Category(models.Model):
    photo = models.ForeignKey("Profile", verbose_name=_("photo"), on_delete=models.CASCADE)
    clinic_photos = models.ImageField(_("صور العياده :"), blank=True, null=True)
    
    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categorys")

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *

class UserCreationForms(UserCreationForm):
    username    = forms.CharField(label = 'الإسم' )
    email       = forms.EmailField(label = 'البريد الالكترونى' )
    first_name  = forms.CharField(label = 'الإسم الاخير' )
    last_name   = forms.CharField(label = 'الإسم الاول' )
    password1   = forms.CharField(label='كلمه السر', widget=forms.PasswordInput() , min_length=8)
    password2   = forms.CharField(label='تأكيد كلمه السر ', widget=forms.PasswordInput() , min_length=8)

    class Meta:
        model   = User
        fields  = ( 'username' ,'first_name' , 'last_name' , 'email' , 'password1' , 'password2' )
 


class Login_Form(forms.ModelForm):
    username = forms.CharField(max_length=80, label="الإسم")
    password = forms.CharField(label="كلمة المرور " , widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = '__all__' 


class UpdateUserForm(forms.ModelForm):
    first_name = forms.CharField(label='الاسم الاول ')
    last_name = forms.CharField(label='الاسم الاخير ')
    email = forms.EmailField(label= 'البريد الاليكترونى ')
    class Meta:
        model   = User
        fields  = ('first_name' , 'last_name' , 'email')



class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model   = Profile
        fields  = ('who_i','name' ,'surname',
                    'subtitle','address','address_detail',
                    'price','number_phone','working_hours',
                    'Waiting_time', 'facebook', 'twitter',
                    'google', 'doctor','img',  'Specialist_doctor')

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from .models import *
from .forms import *
from django.contrib.auth import authenticate , login
from django.contrib.auth.decorators import login_required


# Create your views here.
def doctor_list(request):
    doctors = User.objects.all()
    context = {
        'doctorsHTML': doctors
    }
    return render(request,'user/doctor_list.html',context)



def doctor_details(request , slug):
    doctorDetails = Profile.objects.get(slug = slug)
    context = {
        'doctorDetails': doctorDetails
    }
    return render(request,'user/doctor_details.html',context)


# def user_login(request):
#     if request.method == 'POST':
#         form = Login_Form()
#         username = request.POST('username')
#         password = request.POST('password')
#         user = authenticate(request , username = username , password = password)
#         if user is not None:
#             login(request , user)
#     else:
#         form = Login_Form() 
#         return redirect('accounts:doctor_list')      
#     context = { 
#             'form': form  
#     }
#     return render(request,'user/user_login.html',context)
    
def user_login(request):
    if request.method == 'POST':
        form = Login_Form()
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request ,username=username , password=password)
        if user is not None:
            login(request , user)
            return redirect('accounts:doctor_list')
        # else:
        #     messages.error(request, "كلمه السر غير صحيحه")
    else:
        form = Login_Form()

    return render(request , 'user/user_login.html' , {
        'form' : form,
        'title' : 'تسجيل الدخول'
    })


@login_required()
def myProfile(request):

    context = {

    }
    return render(request,'user/myprofile.html',context)


def updateProfile(request):
    userForm = UpdateUserForm(instance=request.user)
    profileForm = UpdateProfileForm(instance=request.user.profile)
    context = {
        'userForm' : userForm,
        'profileForm': profileForm
        }
    if request.method == 'POST':
        userForm = UpdateUserForm(request.POST , instance=request.user)
        profileForm = UpdateProfileForm(request.POST ,request.FILES ,instance=request.user.profile)

        if userForm.is_valid() and profileForm.is_valid():
            userForm.save()
            profileForm.save()
            return redirect('accounts:doctor_list')
        
    return render(request,'user/update_profile.html',context)


def signUp(request):
    if request.method == 'POST':
        signupform = UserCreationForms(request.POST)
        context = {
        'signupform':signupform
        }
        if signupform.is_valid():
            signupform.save()
            username = signupform.cleaned_data.get('username')
            password = signupform.cleaned_data.get('password')
            user = authenticate(username='username', password='password')
            login(request , user)
            return redirect('accounts:doctor_list')
    else:
        signupform = UserCreationForms()
    return render(request , 'user/signup.html',{
        'signupform':signupform
        })

accounts/templates/user/doctor_details.html
{% extends "main/base.html" %} {% load static %} {% block content %}

<div dir="rtl">
  {% include 'user/search.html' %}
  
<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="job_details_header">
                    <div class="single_jobs white-bg d-flex justify-content-between">
                        <div class="jobs_left d-flex align-items-center">
                            <div >
                                number_phone
                                {% if doctorDetails.img %}
                                    <img class="img-circle" src="{{doctorDetails.img.url}}" alt="" width="100" height="100">
                                {% endif %}
                            </div>
                            <div class="jobs_conetent">
                                <a href="#" ><h4>{{doctorDetails.name}}</h4></a>
                                <div class="links_locat d-flex align-items-center">
                                    <div class="location">
                                        <p> <i class="fa fa-map-marker"></i> مصر  , {{doctorDetails.address}}</p>
                                    </div>
                                    <div class="location">
                                        <p> <i class="fa fa-clock-o"></i>  وقت الانتظار {{doctorDetails.Waiting_time}} دقيقه</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% comment %} <div class="jobs_right">
                            <div class="apply_now">
                                <a class="boxed-btn3" href="{% url 'accounts:appointment' doctorDetails.slug %}">حجز كشف</a>
                            </div>
                        </div> {% endcomment %}
                    </div>
                </div>
                
                <div class="descript_wrap white-bg">
                    <div class="single_wrapp">
                        <h3>{{doctorDetails.subtitle}}</h3>
                    </div>
                    <div class="white-card white-card-inner">
                        <div class="single_wrap" style="margin-top: 10px;">
                            <h4>معلومات عن الدكتور</h4>
                            <ul>
                                <p>{{doctorDetails.who_i}}</p>
                            </ul>
                        </div>
                    </div>
                    <div class="single_wrap">
                        <h4>خدمات الدكتور :</h4>
                        <ul>
                            <p class="tagitem disable-click pull-left mr-4" style="background-color: #f5f5f5;
                            color: #808184;"> استشاري جراحه وتجميل الاسنان 
                            </p>
                            <p class="tagitem disable-click pull-left" style="background-color: #f5f5f5;
                            color: #808184;">استشاري جراحه وتجميل الاسنان 
                            </p>
                        </ul>
                        <br>
                    </div>
                    <div class="single_wrap">
                        <h4>صور العيادة :</h4>
                        {% for img in img_category %}
                            {% if img.clinic_photos %}
                                <img class="img_clinic" src="{{ img.clinic_photos.url }}" alt="" >
                            {% endif %}
                        {% endfor %}
                        
     
    
                    </div>
                </div>
    
        <!-- comments -->
        <div class="section-row">
            <div class="section-title">
                <h2 style="color: brown;">التعليقات ( {{comments.count}} )</h2>
            </div>
    
            <div class="post-comments" >
                {% for comment in comments  %}
                <!-- comment -->
                <div class="media">
                    <div class="media-left">
                        <img class="media-object" src="{% static 'blog/img/avatar.png'%}" alt="">
                    </div>
                    <div class="media-body " >
                        <div class="media-heading">
                            <h4>{{comment.name}}</h4>
                            <span class="time">تم التعليق في {{comment.create_at|date:'d-m-Y'}}</span>
                        </div>
                        <p>{{comment.comments}}</p>
                        <a href="#" class="reply">الردود ..</a>
    
                        <!-- comment -->
                        <div class="media">
                            <div class="media-left">
                                <img class="media-object" src="{% static 'blog/img/avatar.png'%}" alt="">
                            </div>
                            <div class="media-body">
                                <div class="media-heading">
                                    <h4>محمود عبد الرؤف صبره</h4>
                                    <span class="time">March 27, 2018 at 8:00 am</span>
                                    <a href="#" class="reply">Reply</a>
                                </div>
                                <p>شكرا جدا واتمنى ان تتصفح باقي المواقع .....</p>
                            </div>
                        </div>
                        <!-- /comment -->
                    </div>
                </div>
                <!-- /comment -->
                {% empty %}
                <div class="media-heading">
                    <h4>لا يوجد تعليقات حتى الأن ..</h4>
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- /comments -->                    
        <div class="apply_job_form white-bg">
            <h4>إترك تعليقك</h4>
            <form method="POST" >
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        <div class="input_field">
                            <input type="text" name="name"   placeholder=" الإسم">
                            
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="input_field">
                            <input type="text" name="email"   placeholder=" الإيميل">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="input_field">
                            <textarea name="comments"  cols="30" rows="10" placeholder="تعليقك .."></textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="submit_btn">
                            <button class="boxed-btn3 w-100" type="submit">تعليق</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
            </div>
            <div class="col-lg-4">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>معلومات عن الدكتور </h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>  انضم إلينا : <span style="color: blue;">{{doctorDetails.join_us|date:'d - m - Y'}}</span></li>
                            <li> الكشف : <span style="color: blue;">{{doctorDetails.price}} جنية</span></li>
                            <li> رقم الهاتف  : <span style="color: blue;">{{doctorDetails.number_phone}}</span></li>
                            <li>عدد ساعات العمل : <span style="color: blue;">{{doctorDetails.working_hours}} ساعات</span></li>
                        </ul>
                        
                    </div>
                </div>
                <div class="share_wrap d-flex">
                    <span>شارك الصفحه :</span>
                    <ul>
                        <li><a href="{{user.profile.facebook}}"> <i class="fa fa-facebook"></i></a> </li>
                        <li><a href="{{user.profile.facebook}}"> <i class="fa fa-google-plus"></i></a> </li>
                        <li><a href="{{user.profile.facebook}}"> <i class="fa fa-twitter"></i></a> </li>
                        <li><a href="{{user.profile.facebook}}"> <i class="fa fa-envelope"></i></a> </li>
                    </ul>
                </div>
                <div class="job_location_wrap">
                    <div class="job_lok_inner">
                        <div id="map" style="height: 200px;"></div>
                        <script>
                            function initMap() {
                            var uluru = {lat: -25.363, lng: 131.044};
                            var grayStyles = [
                                {
                                featureType: "all",
                                stylers: [
                                    { saturation: -90 },
                                    { lightness: 50 }
                                ]
                                },
                                {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                            ];
                            var map = new google.maps.Map(document.getElementById('map'), {
                                center: {lat: -31.197, lng: 150.744},
                                zoom: 9,
                                styles: grayStyles,
                                scrollwheel:  false
                            });
                            }
                            
                        </script>
                        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                        
                        </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>

    {% endblock content %}

accounts/templates/user/doctor_list.html
{% extends "main/base.html" %} {% load static %} {% block content %}

<div dir="rtl">
  {% include 'user/search.html' %}
  <!-- job_listing_area_start  -->
  <div class="job_listing_area">
    <div class="container">
      <div class="job_lists">
        <div class="row">
          {% for doctor in doctorsHTML %}
          <div class="col-lg-10 col-md-10" style="height: 16rem">
            <div class="single_jobs white-bg d-flex justify-content-between">
              <div class="jobs_left d-flex align-items-center">
                <div>
                    {% if doctor.profile.img %}
                  <img
                    src="{{doctor.profile.img.url}}"
                    alt=""
                    width="100"
                    height="100"
                  />
                  {% else %}
                  <img
                  src="{% static 'staticFile/img/candiateds/1.png' %}"
                  alt=""
                  width="100"
                  height="100"
                />
                  {% endif %}
                </div>
                <div class="jobs_conetent">
                  <a href="{% url 'accounts:doctor_details' doctor.profile.slug%}"><h5> دكتور {{doctor.profile.name}}</h5></a>
                  <h6>{{doctor.profile.subtitle}}</h6>

                  <div class="links_locat">
                    <div class="location">
                      <p>
                        <i class="fas fa-briefcase-medical"></i> دكتور
                        <span style="color: blue">{{doctor.profile.doctor}}</span> متخصص في
                        <span style="color: blue">{{doctor.profile.Specialist_doctor}}</span>
                      </p>
                      <p>
                        <i class="fa fa-map-marker"></i>{{doctor.profile.address}} : {{doctor.profile.address_detail}}
                      </p>
                      <p>
                        <i class="fa fa-map-marker"></i> الكشف :
                        <span style="color: blue">{{doctor.profile.price}}</span> جنية
                      </p>
                      <p>
                        <i class="fa fa-clock-o"></i> مدة الانتظار :
                        <span style="color: blue">{{doctor.profile.Waiting_time}}</span> ساعه
                      </p>
                      <p>
                        <i class="fa fa-clock-o"></i> عدد ساعات العمل :
                        <span style="color: blue">{{doctor.profile.working_hours}}</span> ساعه
                      </p>
                      <p>
                        <i class="fa fa-clock-o"></i>سعر المكالمه العادية :<span
                          style="color: blue"
                        >
                        {{doctor.profile.number_phone}}
                        </span>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="jobs_right">
                <div class="apply_now">
                  <a class="boxed-btn3" href="">حجز كشف</a>
                </div>

                <div class="rating">
                  <div class="text-warning">
                    <!-- to make image category for clinic image -->
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                  </div>
                  <div class="rating">
                    <h5>{{doctor.profile.rating}}</h5>
                  </div>
                </div>
              </div>
              
            </div>
            
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <!-- job_listing_area_end  -->
</div>
<!-- featured_candidates_area_start  -->
<div class="featured_candidates_area">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section_title text-center mb-40">
          <h3>المرشحين المميزين</h3>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <div class="candidate_active owl-carousel">
          <div class="single_candidates text-center">
            <div class="thumb">
              <img class="img-circle" src="img/candiateds/2.png" alt="" />
            </div>
            <a href=""><h4>الاسم</h4></a>
            <p>التخصص</p>
            <div class="best-rating">
              <div class="text-warning">
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
                <i class="fa fa-star"></i>
              </div>
              <div class="best-rating">
                <h5>تقييم الدكتور</h5>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- featured_candidates_area_end  -->

{% endblock content %}

accounts/templates/user/search.html
 <!-- Search -->
 <div class="catagory_area ">
    <div class="container " style="margin-top: 10rem">
                <div class=" single_text">
                    <h2>احجز مع
                        أفضل دكتور في مصر</h3>
                    <h3>احجز اونلاين او كلم  ١٧٧٥۸</h4>
                    <h4>١٦٠٠٠ دكتور -٤٠٠٠ استاذ واستشاري - اكثر من ۲٠ تخصص</h5>
                    <br>
                </div>
                <form  method="GET" action="">
                <div class="row cat_search" >
    
                    <div class="col-lg-3 col-md-4">
                        <div class="single_input">
                            <input type="text" placeholder="إسم الدكتور" >
                        </div>
                    </div>
    
                    <div class="col-lg-3 col-md-4">
                        <div class="single_input">
                            <select class="wide" >
                                <option value="" >الموقع</option>
                                <option value="المنصوره">المنصوره</option>
                                <option value="الدقي">الدقي</option>
                                <option value="4">Sylet</option>
                            </select>
                        </div>
                    </div>
    
                    <div class="col-lg-3 col-md-4">
                        <div class="single_input">
                            <select class="wide" >
                                <option value="">التخصص</option>
                                <option value="جلدية">جلدية</option>
                                <option value="اسنان">اسنان</option>
                                <option value="نفسي">نفسي</option>
                                <option value="اطفال">اطفال حديثي الولادة</option>
                                <option value="مخ">مخ واعصاب</option>
                                <option value="عظام">عظام</option>
                                <option value="نساء">نساء وتوليد</option>
                                <option value="انف">انف واذن وحنجرة</option>
                                <option value="قلب">قلب واوعية دموية</option>
                                <option value="امراض">امراض دم</option>
                                <option value="اورام">اورام</option>
                                <option value="باطنه">باطنه</option>
                                <option value="تخسيس">تخسيس وتغذية</option>
                                <option value="جاطفال">جراحة اطفال</option>
                                <option value="جاورام">جراحة اورام</option>
                                <option value="جاوعيه">جراحة اوعية دموية</option>
                                <option value="جتجميل">جراحة تجميل</option>
                                <option value="سمنه">جراحه سمنة ومناظير </option>
                                </select>
                        </div>
                    </div>
    
                    <div class="col-lg-3 col-md-12">
                        <div class="job_btn">
                            <input type="submit" class="boxed-btn3" value="ابحث هنا">
                        </div>
                    </div>
    
                </div>
                </form> 
            </div>
        </div>
        <!-- endsearch -->

accounts/templates/user/signup.html
{% extends 'main/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div dir="rtl">
<div class="container">
    <div class="signup">

    <div class="col-md-9" >
        <form method="POST" enctype="multipart/form-data">
            <h4 class="auth-header">أنشاء حساب جديد</h4>
            {% csrf_token %}
            <div class="form-group">
                {{ signupform.username|as_crispy_field  }}
            </div>
            <div class="form-group">
                {{ signupform.email|as_crispy_field  }}

            </div>
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        {{ signupform.first_name|as_crispy_field}}
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        {{ signupform.last_name|as_crispy_field}}
                </div>
            </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        {{ signupform.password1|as_crispy_field}}
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        {{ signupform.password2|as_crispy_field}}
                </div>
            </div>
            <div class="buttons-w"><button type="submit" class="btn btn-success">التسجيل</button></div>

        </form>
    </div>
    </div>
</div>
</div>
{% endblock content %}