accounts/urls.py
from django.urls import path
from .views import *
from . import views
app_name = 'accounts'
urlpatterns = [
    path('doctor/',views.doctor_list,name='doctor_list'),
    path('login',views.user_login,name='user_login'),
    path('signup',views.signUp,name='signUp'),
    path('doctor/myprofile',views.myProfile,name='myProfile'),
    path('doctor/updateProfile',views.updateProfile,name='updateProfile'),
    path('doctor/<slug:slug>/',views.doctor_details,name='doctor_details'),
]

vezetaproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls'), name='accounts'),
] 
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.utils.translation import gettext as _


TYPE_OF_PERSON =(
    ( 'M' , "Male"),
    ( 'F' , "Female"),
    )

class Profile(models.Model):

    DOCTOR_IN={
        ( "جلدية" , "جلدية"),
        ( "أسنان" , "أسنان"),
        ( "نفسي" , "نفسي"),
        ( "أطفال حديثي الولادة"  , "أطفال حديثي الولادة"),
        ( "مخ وأعصاب"  , "مخ وأعصاب"),
        (  "عظام" , "عظام"),
        ( "نساء وتوليد"  , "نساء وتوليد"),
        ( "أنف وأذن وحنجرة"   , "أنف وأذن وحنجرة"),
        ( "قلب وأوعيه دموية"   , "قلب وأوعيه دموية"),
        ( "أمراض دم" , "أمراض دم"),
        ( "أورام" , "أورام"),
        ( "باطنة" , "باطنة"),
        ( "تخسيس وتغذية"  , "تخسيس وتغذية"),
        ( "جراحة أطفال"  , "جراحة أطفال"),
        ( "جراحة أورام"  , "جراحة أورام"),
        ( "جراحة أوعيه دموية"   , "جراحة أوعيه دموية"),
        ( "جراحة تجميل"  , "جراحة تجميل"),
        ( "جراحة سمنة ومناظير "   , "جراحة سمنة ومناظير "),
    }
    user            = models.OneToOneField(User,  on_delete=models.CASCADE)
    who_i           = models.TextField(_("من انا"), max_length=250)
    name            = models.CharField(_("الإسم رابعى"), max_length=50)
    surname         = models.CharField(_("اللقب"), max_length=20, blank=True, null=True) 
    subtitle        = models.TextField(_("نبذه عنك"), max_length=70, blank=True, null=True)
    address         = models.CharField(_("المحافظه"), max_length=30, blank=True, null=True)
    address_detail  = models.CharField(_("العنوان بالتفصيل"), max_length=25, blank=True, null=True)
    price           = models.IntegerField(_("سعر الكشف"), blank=True, null=True)
    number_phone    = models.CharField(_("رقم الهاتف"), max_length=50, blank=True, null=True)
    working_hours   = models.CharField(_("عدد ساعات العمل"), max_length=50, blank=True, null=True)
    img           = models.ImageField(_("profile_image"), blank=True, null=True)
    Waiting_time    = models.IntegerField(_("مده الانتظار"), blank=True, null=True)
    facebook        = models.CharField(max_length=100 , blank=True, null=True)
    twitter         = models.CharField(max_length=100 , blank=True, null=True)
    google          = models.CharField(max_length=100 , blank=True, null=True)
    join_us         = models.DateTimeField(_("وقت الانضمام") ,auto_now_add=True ,blank=True, null=True)
    type_doctors    = models.CharField(_("النوع"), choices=TYPE_OF_PERSON, default='M' ,max_length=20, blank=True, null=True)
    doctor          = models.CharField(_("دكتور ؟"),choices=DOCTOR_IN , max_length=50, blank=True, null=True)
    Specialist_doctor = models.CharField(_("متخصص فى ؟"), max_length=50, blank=True, null=True)
    rating          = models.PositiveIntegerField(_("التقييم"),default=0, blank=True, null=True)
    slug            = models.SlugField(_("slug") , blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username)
        super(Profile, self).save(*args, **kwargs)


    def __str__(self):
        return '%s' %(self.user.username)

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'
    
def create_profile(sender , **kwargs):
    if kwargs['created']:
        Profile.objects.create(user=kwargs['instance'])
post_save.connect(create_profile, sender=User)





class Comment(models.Model):
    comment     = models.ForeignKey('Profile' , related_name="author", on_delete=models.CASCADE, null=True, blank=True)
    create_at   = models.DateTimeField(auto_now_add=True , blank=True, null=True)
    name        = models.CharField(_("الإسم"), max_length=50)
    email       = models.EmailField(_("الإيميل"), max_length=50)
    comments    = models.TextField(_("التعليق") , max_length=250)

    def __str__(self):
        return '%s' %(self.name)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        ordering = ('-create_at',)

class Appointment(models.Model):
    doctor      = models.ForeignKey('Profile',related_name="doc" , verbose_name=_("doctor"), on_delete=models.CASCADE  , blank=True, null=True)
    name        = models.CharField(_("الإسم") , max_length=100)
    number      = models.CharField(_("رقم الهاتف") , max_length=20)
    email       = models.EmailField(_("الإيميل"), max_length=50)
    read        = models.BooleanField(_("تمت القراءة"), blank=True, null=True)

    def __str__(self):
        return self.name



class Category(models.Model):
    photo = models.ForeignKey("Profile", verbose_name=_("photo"), on_delete=models.CASCADE)
    clinic_photos = models.ImageField(_("صور العياده :"), blank=True, null=True)
    
    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categorys")

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *

class UserCreationForms(UserCreationForm):
    username    = forms.CharField(label = 'الإسم' )
    email       = forms.EmailField(label = 'البريد الالكترونى' )
    first_name  = forms.CharField(label = 'الإسم الاخير' )
    last_name   = forms.CharField(label = 'الإسم الاول' )
    password1   = forms.CharField(label='كلمه السر', widget=forms.PasswordInput() , min_length=8)
    password2   = forms.CharField(label='تأكيد كلمه السر ', widget=forms.PasswordInput() , min_length=8)

    class Meta:
        model   = User
        fields  = ( 'username' ,'first_name' , 'last_name' , 'email' , 'password1' , 'password2' )
 


class Login_Form(forms.ModelForm):
    username = forms.CharField(max_length=80, label="الإسم")
    password = forms.CharField(label="كلمة المرور " , widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = '__all__' 


class UpdateUserForm(forms.ModelForm):
    first_name = forms.CharField(label='الاسم الاول ')
    last_name = forms.CharField(label='الاسم الاخير ')
    email = forms.EmailField(label= 'البريد الاليكترونى ')
    class Meta:
        model   = User
        fields  = ('first_name' , 'last_name' , 'email')



class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model   = Profile
        fields  = ('who_i','name' ,'surname',
                    'subtitle','address','address_detail',
                    'price','number_phone','working_hours',
                    'Waiting_time', 'facebook', 'twitter',
                    'google', 'doctor','img',  'Specialist_doctor')

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from .models import *
from .forms import *
from django.contrib.auth import authenticate , login
from django.contrib.auth.decorators import login_required


# Create your views here.
def doctor_list(request):
    doctors = User.objects.all()
    context = {
        'doctorsHTML': doctors
    }
    return render(request,'user/doctor_list.html',context)



def doctor_details(request , slug):
    doctorDetails = Profile.objects.get(slug = slug)
    context = {
        'doctorDetails': doctorDetails
    }
    return render(request,'user/doctor_details.html',context)


# def user_login(request):
#     if request.method == 'POST':
#         form = Login_Form()
#         username = request.POST('username')
#         password = request.POST('password')
#         user = authenticate(request , username = username , password = password)
#         if user is not None:
#             login(request , user)
#     else:
#         form = Login_Form() 
#         return redirect('accounts:doctor_list')      
#     context = { 
#             'form': form  
#     }
#     return render(request,'user/user_login.html',context)
    
def user_login(request):
    if request.method == 'POST':
        form = Login_Form()
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request ,username=username , password=password)
        if user is not None:
            login(request , user)
            return redirect('accounts:doctor_list')
        # else:
        #     messages.error(request, "كلمه السر غير صحيحه")
    else:
        form = Login_Form()

    return render(request , 'user/user_login.html' , {
        'form' : form,
        'title' : 'تسجيل الدخول'
    })


@login_required()
def myProfile(request):

    context = {

    }
    return render(request,'user/myprofile.html',context)


def updateProfile(request):
    userForm = UpdateUserForm(instance=request.user)
    profileForm = UpdateProfileForm(instance=request.user.profile)
    context = {
        'userForm' : userForm,
        'profileForm': profileForm
        }
    if request.method == 'POST':
        userForm = UpdateUserForm(request.POST , instance=request.user)
        profileForm = UpdateProfileForm(request.POST ,request.FILES ,instance=request.user.profile)

        if userForm.is_valid() and profileForm.is_valid():
            userForm.save()
            profileForm.save()
            return redirect('accounts:doctor_list')
        
    return render(request,'user/update_profile.html',context)


def signUp(request):
    if request.method == 'POST':
        signupform = UserCreationForms(request.POST)
        context = {
        'signupform':signupform
        }
        if signupform.is_valid():
            signupform.save()
            username = signupform.cleaned_data.get('username')
            password = signupform.cleaned_data.get('password')
            user = authenticate(username='username', password='password')
            login(request , user)
            return redirect('accounts:doctor_list')
    else:
        signupform = UserCreationForms()
    return render(request , 'user/signup.html',{
        'signupform':signupform
        })

accounts/templates/main/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">



    <title>Vezeta</title>

    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'staticFile/img/favicon.png'%}">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'staticFile/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'staticFile/css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'staticFile/css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'staticFile/css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'staticFile/css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'staticFile/css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'staticFile/css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'staticFile/css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'staticFile/css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'staticFile/css/slicknav.css'%}">

    <link rel="stylesheet" href="{% static 'staticFile/css/style.css' %}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>

<!-- header-start -->
<header>
<div class="header-area ">
    <div id="sticky-header" class="main-header-area">
        <div class="container-fluid " style="background-color: rgba(0, 29, 56, 0.8);" >
            <div class="header_bottom_border">
                <div class="row align-items-center">
                    <div class="col-xl-3 col-lg-2">
                        <div class="logo">
                            <a href="index.html">
                                <img src="{% static 'staticFile/img/logo2.png' %}" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-7">
                        <div class="main-menu  d-none d-lg-block">
                            <nav>
                                <ul id="navigation">
                                    <li><a href="{% url 'accounts:doctor_list' %}">احجز دكتورك</a></li>|
                                    <li><a href="">المقالات</a></li>|
                                    <li><a href="{% url 'accounts:myProfile' %}">الصفحه الشخصيه </a></li>|
                                    <li><a href="contact.html">اتصل بنا</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                        <div class="Appointment">


                            {% if user.is_authenticated %}
                            <div class="phone_num d-none d-xl-block"></div>
                            <div class="d-none d-lg-block">
                                <a class="boxed-btn3" href="">قدم نفسك</a>
                            </div>
                            {% else %}
                            <div class="phone_num d-none d-xl-block">
                                <a class="boxed-btn3" href="">سجل الدخول</a>
                            </div>
                            <div class="d-none d-lg-block">
                                <a class="boxed-btn3" style="background-color: crimson;" href="">التسجيل</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</header>
<!-- header-end -->

{% block content %}

{% endblock content %}


<!-- footer start -->
<footer class="footer">
    <div class="footer_top">
    <div class="container">
        <div class="row">
            <div class="col-xl-3 col-md-6 col-lg-3">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                    <div class="footer_logo">
                        <a href="#">
                            <img src="{% static 'staticFile/img/logo2.png' %}" alt="">
                        </a>
                    </div>
                    <p>
                        eng.mostafa.mohamed.salama@gmail.com <br>
                        +01204903938 <br>
                        Alexandria, Egypt
                    </p>
                    <div class="socail_links">
                        <ul>
                            <li>
                                <a href="https://www.facebook.com/m7modsabra">
                                    <i class="ti-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.youtube.com/channel/UC7FFcZc90vE5FfR_dgA_dVg?view_as=subscriber">
                                    <i class="fa fa-youtube"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/Mahmod_Raouf">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://twitter.com/Mahmod_Raouf">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-xl-2 col-md-6 col-lg-2">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                    <h3 class="footer_title">
                        ماذا عنا
                    </h3>
                    <ul>
                     
                    </ul>
    
                </div>
            </div>
            <div class="col-xl-3 col-md-6 col-lg-3">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                    <h3 class="footer_title">
                        الخدمات
                    </h3>
                  
                </div>
            </div>
            <div class="col-xl-4 col-md-6 col-lg-4">
                <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                    <h3 class="footer_title">
                        Subscribe
                    </h3>
                    <form action="#" class="newsletter_form">
                        <input type="text" placeholder="Enter your mail">
                        <button type="submit">Subscribe</button>
                    </form>
                    <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                        luckily.</p>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
    <div class="container">
        <div class="footer_border"></div>
        <div class="row">
            <div class="col-xl-12">
                <p class="copy_right text-center">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
    </div>
    </footer>
    <!--/ footer end  -->
    
    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'staticFile/js/vendor/modernizr-3.5.0.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/vendor/jquery-1.12.4.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/popper.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/bootstrap.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/owl.carousel.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/isotope.pkgd.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/ajax-form.js"'%}"></script>
    <script src="{% static 'staticFile/js/waypoints.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/jquery.counterup.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/imagesloaded.pkgd.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/scrollIt.js"'%}"></script>
    <script src="{% static 'staticFile/js/jquery.scrollUp.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/wow.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/nice-select.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/jquery.slicknav.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/jquery.magnific-popup.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/plugins.js"'%}"></script>
    <script src="{% static 'staticFile/js/gijgo.min.js"'%}"></script>
    
    
    
    <!--contact js-->
    <script src="{% static 'staticFile/js/contact.js"'%}"></script>
    <script src="{% static 'staticFile/js/jquery.ajaxchimp.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/jquery.form.js"'%}"></script>
    <script src="{% static 'staticFile/js/jquery.validate.min.js"'%}"></script>
    <script src="{% static 'staticFile/js/mail-script.js"'%}"></script>
    
    
    <script src="{% static 'staticFile/js/main.js"'%}"></script>
    </body>
    
    </html>